version: "3"
services:
  order:
    image: sergiuvictor/courier_service:v1.0
    ports:
      - '8083:8080'
    depends_on:
      - mysqldb
    environment:
      spring.datasource.url: jdbc:mysql://mysqldb:3306/courier_orders
  user:
    image: sergiuvictor/user_service:v1.0
    ports:
      - '8084:8080'
    depends_on:
      - mysqldb2
    environment:
      spring.datasource.url: jdbc:mysql://mysqldb2:3306/users_schema

  mysqldb2:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=users_schema

  mysqldb:
    image: mysql:8
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=courier_orders