apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  users_db_url: jdbc:mysql://users-db-service:3306/users_schema?createDatabaseIfNotExist=true
  couriers_db_url: jdbc:mysql://couriers-db-service:3306/courier_orders?createDatabaseIfNotExist=true