apiVersion: v1
kind: PersistentVolume
metadata:
  name: users-pv
  labels:
    type: local
spec:
  storageClassName: users-db
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/db"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-pvc
spec:
  storageClassName: users-db
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-mysql
spec:
  selector:
    matchLabels:
      app: users-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: users-mysql
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: users-secret
                  key: users_db_password
          ports:
            - containerPort: 3307
              name: users-port

          volumeMounts:
            - name: users-db-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: users-db-storage
          persistentVolumeClaim:
            claimName: users-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: users-db-service
spec:
  ports:
    - port: 3307
      targetPort: 3307
  selector:
    app: users-mysql
  clusterIP: None